defaults: &defaults
  site_name: Qiang Blog
  site_desc: Just another zhangjingqiang's blog.
  
  twitter: https://twitter.com/zhangjingqiang
  facebook: https://www.facebook.com/zhangjingqiang
  about_me: http://about.me/zhangjingqiang
  
  addthis: zhangjingqiang
  disqus: qiang-blog

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults