defaults: &defaults
  site_name: Qiang Blog
  site_desc: Just another <%= ENV['AUTHOR'] %>'s blog.

  twitter: https://twitter.com/<%= ENV['TWITTER'] %>
  facebook: https://www.facebook.com/<%= ENV['FACEBOOK'] %>
  about_me: http://about.me/<%= ENV['ABOUT_ME'] %>

  addthis: <%= ENV['ADDTHIS'] %>
  disqus: <%= ENV['DISQUS'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
